apiVersion: v2
name: lm-logs
description: A Helm chart for sending k8s logs to Logic Monitor

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.1-devel
