{{- if eq .Values.logs.enable true}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "lmotel.fullname" . }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.logs.image.repository }}:{{ .Values.logs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.arguments}}
          args:  
            {{ range .Values.arguments }}
              - {{ . }}
            {{ end }}
          {{- end }}                            
          env:
            - name: LOGICMONITOR_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_account
            - name: LOGICMONITOR_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_bearer_token
                  optional: true
            - name: LOGICMONITOR_ACCESS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_access_id
                  optional: true
            - name: LOGICMONITOR_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_access_key
                  optional: true                
            - name: LOGICMONITOR_OTEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_otel_name                  
            - name: LOGICMONITOR_OTEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_version
                  optional: true
            - name: LOGICMONITOR_OTEL_NAMESPACE
              value: {{ .Release.Namespace }}
          {{- if .Values.external_config.lmconfig}}
          args: 
              - --config
              - lmconfig.yaml
              {{- if .Values.arguments}}  
              {{ range .Values.arguments }}
              - {{ . }}
              {{ end }}
              {{- end }}
            {{- end }}
          volumeMounts:
                 {{- toYaml .Values.volumeMounts | nindent 12 }}
                 {{- if .Values.external_config.lmconfig}}
                  - name: {{ .Release.Name }}
                    mountPath: lmconfig.yaml
                    subPath: lmconfig.yaml
                 {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
          {{- toYaml .Values.volumes | nindent 8 }}
          {{- if .Values.external_config.lmconfig}}
            - name: {{ .Release.Name }}
              configMap:
                name: {{ .Release.Name }}
                items:
                  - key: lmconfig.yaml
                    path: lmconfig.yaml
          {{- end }}
{{- end }}