apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
type: Opaque
data:
  {{- if .Values.lm.bearer_token}}
  lm_bearer_token: {{ .Values.lm.bearer_token | b64enc }}
  {{ end }}
  {{- if .Values.lm.access_id}}
  lm_access_key: {{ .Values.lm.access_key | b64enc }}
  {{ end }}
