{{- if eq .Values.logs.enable false}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lmotel.fullname" . }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
spec:
# servicename used only in case of statefulset
  serviceName: {{ .Release.Name }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.arguments}}
          args:  
            {{ range .Values.arguments }}
              - {{ . }}
            {{ end }}
          {{- end }}
          env:
            - name: LOGICMONITOR_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_account
            - name: LOGICMONITOR_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_bearer_token
                  optional: true
            - name: LOGICMONITOR_ACCESS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_access_id
                  optional: true
            - name: LOGICMONITOR_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_access_key
                  optional: true                
            - name: LOGICMONITOR_OTEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_otel_name                  
            - name: LOGICMONITOR_OTEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: lm_version
                  optional: true
            - name: LOGICMONITOR_OTEL_NAMESPACE
              value: {{ .Release.Namespace }}
          {{- if .Values.external_config.lmconfig}}
          args: 
              - --config
              - lmconfig.yaml
              {{- if .Values.arguments}}  
              {{ range .Values.arguments }}
              - {{ . }}
              {{ end }}
              {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}
              mountPath: lmconfig.yaml
              subPath: lmconfig.yaml
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.external_config.lmconfig}}
        - name: {{ .Release.Name }}
          configMap:
            name: {{ .Release.Name }}
            items:
              - key: lmconfig.yaml
                path: lmconfig.yaml
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}