{{- if .Values.enableRBAC -}}
---
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: collectorset-controller
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - "*"
- apiGroups:
    - "apps"
  resources:
    - statefulsets
  verbs:
    - "*"
- apiGroups:
    - "*"
  resources:
    - collectorsets
  verbs:
    - "*"
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: collectorset-controller
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collectorset-controller
subjects:
- kind: ServiceAccount
  name: collectorset-controller
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: collector
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - containers
  - nodes
  - nodes/proxy
  - nodes/metrics
  - componentstatuses
  - replicasets
  - ingresses
  - services
  - endpoints
  - pods/log
  - events
  verbs:
  - list
  - get
- apiGroups:
  - "apps"
  - "extensions"
  resources:
  - deployments
  verbs:
  - list
  - get
- apiGroups:
    - "autoscaling"
  resources:
    - horizontalpodautoscalers
  verbs:
    - list
    - get
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
    - "networking.k8s.io"
  resources:
    - ingresses
    - networkpolicies
  verbs:
    - list
    - get
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - list
  - get
- nonResourceURLs:
  - /
  - /healthz
  - /healthz/*
  - /metrics
  - /proxy
  verbs:
  - get
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: collector
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: {{ .Release.Namespace }}
{{- end -}}
