---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collectorset-controller
  namespace: {{ .Release.Namespace }}
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
