---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: releasemanager
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - list
- apiGroups:
    - ""
  resources:
    - pods/portforward
  verbs:
    - create

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: releasemanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: releasemanager
subjects:
- kind: ServiceAccount
  name: releasemanager
  namespace: {{ .Release.Namespace }}
