{{- if .Values.enableRBAC -}}
---
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ .Release.Name }}
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - containers
    - nodes
    - services
    - namespaces
    - componentstatuses
    - configmaps
  verbs:
    - list
    - get
    - watch
    - update
- apiGroups:
    - "apps"
  resources:
    - deployments
  verbs:
    - list
    - get
    - watch
    - update
- apiGroups:
    - "autoscaling"
  resources:
    - horizontalpodautoscalers
  verbs:
    - list
    - get
    - watch
    - update
- nonResourceURLs:
    - /
    - /healthz
    - /healthz/*
  verbs:
    - get
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
