---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | nindent 2 }}
