apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd.serviceAccountName" . }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}

---
apiVersion: {{ include "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "fluentd.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: {{ include "rbac.apiVersion" . }}
metadata:
  name: {{ include "fluentd.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "fluentd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}