apiVersion: v2
description: Automated collector management
name: collectorset-controller
version: 1.4.0-devel
kubeVersion: ">= 1.14.0-0"
maintainers:
- name: LogicMonitor
  email: argus@logicmonitor.com
icon: https://logicmonitor.github.io/k8s-helm-charts/lm_logo.png
dependencies:
  - name: lmutil
    repository: https://logicmonitor.github.io/helm-charts
    # uncomment to test umbrella chart in while developing
    # repository: file://../lmutil
    version: 0.1.6